# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07c41a3c4b170dcf707272cd940b031a33c73d0d411200e0abef7b16158ea5f8bd6e40098b7768e2414cf73ebc6fc5d9d48d6ad06adfb1d1d2b26928564e7fcd

test:
  secret_key_base: a2fc60ee42c93de9f6f8441072f0eacde7c427c7e228b7f870c53f691bb43892abadd3ed3bcb097b2467b563cc449176b6a39933ea0037d64420f048e3f8b648

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
